### ISSUE TITLE
avoid using node's HTTP/HTTPS modules

### ISSUE THREAD

**Issue by diracdeltas** [brave-intl/bat-balance#1]
in browser-laptop, this code bypasses the system proxy: https://github.com/brave-intl/bat-balance/blob/master/index.js#L137

related: https://github.com/brave/browser-laptop/issues/2103

see browser-laptop/js/lib/request for a module which respects the proxy settings

**Comment by diracdeltas** [comment]
An easy way to prevent this is to throw an error if the caller does not provide the 'roundtrip' option, instead of falling back to Node http/https modules.

**Comment by mrose17** [comment]
fixed in 0.9.15
